/** A small vault like Jon's: four Angular notes, each leading its own linked family, among unrelated subjects. */
export interface TopicFixtureDocument { id: string; title: string; text: string; parentId?: string }

const doc = (id: string, title: string, text: string, parentId?: string): TopicFixtureDocument => ({ id, title, text, ...(parentId ? { parentId } : {}) });

export const TOPIC_FIXTURE: TopicFixtureDocument[] = [
  doc("angular", "Angular", "Angular is a TypeScript framework from Google for building single-page applications. An Angular application is a tree of components. Each component pairs a TypeScript class with an HTML template and styles, and Angular renders the template and keeps it in sync with the class through data binding. Services hold shared logic and state; Angular provides them to components through dependency injection. Angular modules (NgModules) used to group components, though standalone components now import what they need directly. The Angular router maps URLs to components and can lazy load feature routes. RxJS observables carry async data such as HTTP responses, and signals are Angular's newer reactive primitive. The Angular CLI scaffolds projects, generates components and services, runs the dev server and builds production bundles."),
  doc("angular-cli", "Angular CLI commands", "ng new creates a workspace, ng generate component adds a component, ng serve starts the dev server and ng build produces the production bundle.", "angular"),
  doc("angular-di", "Dependency injection", "Services are provided in root or in a component's providers array. The injector resolves constructor parameters or the inject() function. Angular creates one instance per injector.", "angular"),
  doc("angular-signals", "Signals", "Signals hold reactive values. computed() derives values and effect() runs side effects when the signals it reads change. Angular change detection can use signals instead of zone.js.", "angular"),

  doc("mf", "Angular module federation", "Module federation lets an Angular shell application load separately built and deployed Angular applications, called remotes, at runtime. It is a webpack feature, and @angular-architects/module-federation wires it into the Angular CLI. Each remote's webpack config exposes modules or standalone components, and the shell's routes call loadRemoteModule to fetch the remote entry and lazy load the exposed routes. Shared dependencies such as @angular/core, @angular/common, @angular/router and rxjs are declared with singleton: true so the shell and every remote use one copy of Angular. Version mismatches between the shell and a remote are the most common source of runtime errors, so keep Angular versions aligned. Native federation is the newer alternative that works with the Angular esbuild builder."),
  doc("mf-shell", "Shell app routes", "The shell's routes call loadRemoteModule with the remote entry URL and exposed module, then lazy load the remote's routes.", "mf"),
  doc("mf-shared", "Sharing dependencies", "shareAll with singleton true and strictVersion keeps one copy of @angular/core and rxjs across the shell and remotes.", "mf"),

  doc("viewchild", "ViewChild", "In Angular, @ViewChild is a property decorator that queries the component's template for a child component, a directive or a DOM element. Angular sets the property once the view is initialized, so read it in ngAfterViewInit; with static: true it is available earlier, in ngOnInit, as long as the element is not inside an *ngIf or *ngFor. Use the read option to ask for a different token, for example ElementRef or ViewContainerRef. @ViewChildren returns a QueryList of every match. Newer Angular versions add viewChild() and viewChildren(), signal-based queries that replace the decorators. ViewChild only sees the component's own template; to query projected content use @ContentChild instead."),
  doc("viewchildren", "ViewChildren and QueryList", "@ViewChildren returns a QueryList of every matching child in the template, and its changes observable emits when the list changes.", "viewchild"),
  doc("elementref", "ElementRef", "ElementRef wraps a native DOM element. Read it with @ViewChild('box', { read: ElementRef }) and avoid touching nativeElement directly where Renderer2 will do.", "viewchild"),

  doc("components", "Angular components", "A component is the basic building block of an Angular application. It is a TypeScript class marked with the @Component decorator, which sets the component's selector, its template and its styles. Angular creates the component wherever its selector appears in another component's template. @Input properties pass data from the parent component down and @Output properties emit events back up. Angular calls lifecycle hooks such as ngOnInit, ngOnChanges, ngAfterViewInit and ngOnDestroy as the component is created, updated and destroyed. Standalone components declare their own imports, so they no longer need an NgModule. Change detection decides when Angular re-renders a component; OnPush limits it to input changes and events."),
  doc("inputs", "Inputs and outputs", "@Input marks a property the parent binds to; @Output with an EventEmitter sends events to the parent. Signal inputs use input() and output().", "components"),
  doc("lifecycle", "Lifecycle hooks", "ngOnChanges, ngOnInit, ngDoCheck, ngAfterContentInit, ngAfterViewInit and ngOnDestroy run in that order.", "components"),

  doc("react", "React hooks", "Hooks let React function components keep state and run side effects. useState returns a state value and a setter, and React re-renders the component when the setter is called. useEffect runs after render and can return a cleanup function. useMemo and useCallback cache values and functions between renders, and useRef keeps a mutable value that does not trigger a re-render. useContext reads a value from the nearest provider. Hooks must be called in the same order on every render, so never call them inside conditions or loops. Custom hooks are plain functions whose names start with use and that call other hooks, which is how React shares stateful logic between components."),
  doc("react-effects", "useEffect cleanup", "Return a cleanup function from useEffect to unsubscribe or clear timers before the effect runs again or the component unmounts.", "react"),
  doc("react-memo", "Memoization", "React.memo skips rerendering a component when its props are unchanged; useCallback keeps a function identity stable.", "react"),

  doc("sourdough", "Sourdough bread", "Feed the starter the night before. Mix flour, water and salt, stretch and fold every half hour, then shape the loaf and proof it overnight in the fridge. Bake in a Dutch oven at 250 C."),
  doc("starter", "Starter feeding schedule", "Equal parts flour and water by weight, twice a day at room temperature, once a week in the fridge.", "sourdough"),
  doc("marathon", "Marathon training plan", "Sixteen weeks: build weekly mileage by ten percent, one long run every Sunday, a tempo run midweek, and taper for the last three weeks before race day."),
  doc("k8s", "Kubernetes deployments", "A Kubernetes Deployment describes the desired state of an application: which container image to run, how many replicas, and how to roll out changes. The Deployment controller manages ReplicaSets, which in turn manage pods. Changing the pod template starts a rolling update that replaces pods gradually, and kubectl rollout status watches its progress while kubectl rollout undo rolls back. Readiness probes keep traffic away from pods that are not ready, and liveness probes restart stuck containers. Resource requests and limits tell the scheduler how much CPU and memory each pod needs."),
  doc("stripe", "Stripe billing", "Create a customer, attach a payment method and start a subscription. Webhooks report invoice.paid and customer.subscription.updated events."),
  doc("asyncio", "Python asyncio", "asyncio is Python's library for writing concurrent code with async and await. An async def function is a coroutine; calling it returns a coroutine object that runs only when awaited or wrapped in a task. The event loop runs one coroutine at a time and switches whenever one awaits I/O. asyncio.gather runs several coroutines concurrently and returns their results, asyncio.create_task schedules a coroutine in the background, and asyncio.run starts the event loop for a program. Blocking calls stall every coroutine on the loop, so run them in a thread with asyncio.to_thread."),
  doc("trip", "Japan trip", "Tokyo for four days, then the Shinkansen to Kyoto. Book the ryokan in Hakone and get a Suica card at the airport."),
  doc("budget", "Monthly budget", "Rent, groceries, utilities and savings. Move the leftover into the index fund at the end of each month."),
];

export function topicFixtureConnections() {
  return TOPIC_FIXTURE.flatMap((document) => document.parentId ? [{ sourceId: document.parentId, targetId: document.id }] : []);
}
